/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StudioIndexRouteImport } from './routes/studio.index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as ToolsStoryboardGeneratorRouteImport } from './routes/tools/storyboard-generator'
import { Route as StudioSplatRouteImport } from './routes/studio.$'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as ApiGenerateStoryboardRouteImport } from './routes/api/generate-storyboard'
import { Route as ApiContactRouteImport } from './routes/api/contact'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiAssistantModifyRouteImport } from './routes/api/assistant-modify'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioIndexRoute = StudioIndexRouteImport.update({
  id: '/studio/',
  path: '/studio/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsStoryboardGeneratorRoute =
  ToolsStoryboardGeneratorRouteImport.update({
    id: '/tools/storyboard-generator',
    path: '/tools/storyboard-generator',
    getParentRoute: () => rootRouteImport,
  } as any)
const StudioSplatRoute = StudioSplatRouteImport.update({
  id: '/studio/$',
  path: '/studio/$',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateStoryboardRoute = ApiGenerateStoryboardRouteImport.update({
  id: '/api/generate-storyboard',
  path: '/api/generate-storyboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiContactRoute = ApiContactRouteImport.update({
  id: '/api/contact',
  path: '/api/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAssistantModifyRoute = ApiAssistantModifyRouteImport.update({
  id: '/api/assistant-modify',
  path: '/api/assistant-modify',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/portfolio': typeof PortfolioRoute
  '/privacy': typeof PrivacyRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/api/assistant-modify': typeof ApiAssistantModifyRoute
  '/api/chat': typeof ApiChatRoute
  '/api/contact': typeof ApiContactRoute
  '/api/generate-storyboard': typeof ApiGenerateStoryboardRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/studio/$': typeof StudioSplatRoute
  '/tools/storyboard-generator': typeof ToolsStoryboardGeneratorRoute
  '/blog/': typeof BlogIndexRoute
  '/studio/': typeof StudioIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/portfolio': typeof PortfolioRoute
  '/privacy': typeof PrivacyRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/api/assistant-modify': typeof ApiAssistantModifyRoute
  '/api/chat': typeof ApiChatRoute
  '/api/contact': typeof ApiContactRoute
  '/api/generate-storyboard': typeof ApiGenerateStoryboardRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/studio/$': typeof StudioSplatRoute
  '/tools/storyboard-generator': typeof ToolsStoryboardGeneratorRoute
  '/blog': typeof BlogIndexRoute
  '/studio': typeof StudioIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/portfolio': typeof PortfolioRoute
  '/privacy': typeof PrivacyRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/api/assistant-modify': typeof ApiAssistantModifyRoute
  '/api/chat': typeof ApiChatRoute
  '/api/contact': typeof ApiContactRoute
  '/api/generate-storyboard': typeof ApiGenerateStoryboardRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/studio/$': typeof StudioSplatRoute
  '/tools/storyboard-generator': typeof ToolsStoryboardGeneratorRoute
  '/blog/': typeof BlogIndexRoute
  '/studio/': typeof StudioIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/portfolio'
    | '/privacy'
    | '/services'
    | '/sitemap.xml'
    | '/terms'
    | '/api/assistant-modify'
    | '/api/chat'
    | '/api/contact'
    | '/api/generate-storyboard'
    | '/blog/$slug'
    | '/studio/$'
    | '/tools/storyboard-generator'
    | '/blog/'
    | '/studio/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/portfolio'
    | '/privacy'
    | '/services'
    | '/sitemap.xml'
    | '/terms'
    | '/api/assistant-modify'
    | '/api/chat'
    | '/api/contact'
    | '/api/generate-storyboard'
    | '/blog/$slug'
    | '/studio/$'
    | '/tools/storyboard-generator'
    | '/blog'
    | '/studio'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/portfolio'
    | '/privacy'
    | '/services'
    | '/sitemap.xml'
    | '/terms'
    | '/api/assistant-modify'
    | '/api/chat'
    | '/api/contact'
    | '/api/generate-storyboard'
    | '/blog/$slug'
    | '/studio/$'
    | '/tools/storyboard-generator'
    | '/blog/'
    | '/studio/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  PortfolioRoute: typeof PortfolioRoute
  PrivacyRoute: typeof PrivacyRoute
  ServicesRoute: typeof ServicesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  ApiAssistantModifyRoute: typeof ApiAssistantModifyRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiContactRoute: typeof ApiContactRoute
  ApiGenerateStoryboardRoute: typeof ApiGenerateStoryboardRoute
  BlogSlugRoute: typeof BlogSlugRoute
  StudioSplatRoute: typeof StudioSplatRoute
  ToolsStoryboardGeneratorRoute: typeof ToolsStoryboardGeneratorRoute
  BlogIndexRoute: typeof BlogIndexRoute
  StudioIndexRoute: typeof StudioIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio/': {
      id: '/studio/'
      path: '/studio'
      fullPath: '/studio/'
      preLoaderRoute: typeof StudioIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/storyboard-generator': {
      id: '/tools/storyboard-generator'
      path: '/tools/storyboard-generator'
      fullPath: '/tools/storyboard-generator'
      preLoaderRoute: typeof ToolsStoryboardGeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio/$': {
      id: '/studio/$'
      path: '/studio/$'
      fullPath: '/studio/$'
      preLoaderRoute: typeof StudioSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-storyboard': {
      id: '/api/generate-storyboard'
      path: '/api/generate-storyboard'
      fullPath: '/api/generate-storyboard'
      preLoaderRoute: typeof ApiGenerateStoryboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/contact': {
      id: '/api/contact'
      path: '/api/contact'
      fullPath: '/api/contact'
      preLoaderRoute: typeof ApiContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/assistant-modify': {
      id: '/api/assistant-modify'
      path: '/api/assistant-modify'
      fullPath: '/api/assistant-modify'
      preLoaderRoute: typeof ApiAssistantModifyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  PortfolioRoute: PortfolioRoute,
  PrivacyRoute: PrivacyRoute,
  ServicesRoute: ServicesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  ApiAssistantModifyRoute: ApiAssistantModifyRoute,
  ApiChatRoute: ApiChatRoute,
  ApiContactRoute: ApiContactRoute,
  ApiGenerateStoryboardRoute: ApiGenerateStoryboardRoute,
  BlogSlugRoute: BlogSlugRoute,
  StudioSplatRoute: StudioSplatRoute,
  ToolsStoryboardGeneratorRoute: ToolsStoryboardGeneratorRoute,
  BlogIndexRoute: BlogIndexRoute,
  StudioIndexRoute: StudioIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
